viewBinding - add view binding in project
polinas888/PerfectWeatherAllYear pull request #1
Opened 2021-10-18 07:06 UTC by polinas888

2021-10-18 14:19 UTC, EVIL-SnaKe requested changes

2021-10-18 14:19 UTC, EVIL-SnaKe commented on app/src/main/java/com/example/perfectweatherallyear/ui/weekWeather/WeekWeatherFragment.kt
> +        binding.weatherForecastRecyclerView.layoutManager = LinearLayoutManager(requireContext())
use scope function with(binding) { }

2021-10-18 14:19 UTC, EVIL-SnaKe commented on app/src/main/java/com/example/perfectweatherallyear/ui/weekWeather/WeatherForecastAdapter.kt
> +            viewHolder.binding.maxMinTempretureTextView.text = weatherList[position].temperature
Use scope function to viewHolder

2021-10-18 14:19 UTC, EVIL-SnaKe commented on app/src/main/java/com/example/perfectweatherallyear/ui/weekWeather/WeatherForecastAdapter.kt
> +    class ViewHolder(val binding: WeatherRowItemBinding, private val onItemListener: OnItemListener) : RecyclerView.ViewHolder(binding.root), View.OnClickListener {
Move this class to the bottom of the file

2021-10-18 14:19 UTC, EVIL-SnaKe commented on app/src/main/java/com/example/perfectweatherallyear/ui/weekWeather/WeatherForecastAdapter.kt
>  class WeatherForecastAdapter(private val dayOfWeekList: List<String>, private val weatherList: List<DayWeather>, onItemListener: ViewHolder.OnItemListener) :
Change constructor to receive one data argument: Map<String, DayWeather>

2021-10-19 10:23 UTC, EVIL-SnaKe commented on app/src/main/java/com/example/perfectweatherallyear/ui/weekWeather/WeekWeatherFragment.kt
> +        val currentDayWeather = weekWeatherMap.get(weekWeatherMap.keys.toTypedArray()[position])
```suggestion
val currentDayWeather = weekWeatherMap[weekWeatherMap.keys.toTypedArray()[position]]
```

2021-10-19 10:23 UTC, EVIL-SnaKe commented on app/src/main/java/com/example/perfectweatherallyear/ui/weekWeather/WeekWeatherFragment.kt
> +        val dayWeather = currentDayWeather?.let { DayWeather(temperature = it.temperature,
Looks like object dayWeather is redundant. You can use already existed val currentDayWeather.

2021-10-19 11:13 UTC, polinas888 commented on app/src/main/java/com/example/perfectweatherallyear/MainActivity.kt
> +        setContentView(binding.root)
gghj

2021-10-19 14:34 UTC, merged